### ISSUE TITLE
USER STORY: Add Review

### ISSUE THREAD

**Issue by OlgaKuvs** [OlgaKuvs/T-studio#17]
Epic: #16 

As a  **user**, I can **post reviews on items that I have purchased** so that **I can advise others if this product is worth purchasing.**

**Acceptance Criteria:**

- Customers should be able to post a review of products. 
- The user must be logged in and have purchased the item to be able to make the review.

**Tasks:**

* [x] create a review model.
* [x] create django form and html page to show this form.
* [x] implement functionality to save reviews to the database.

**Comment by OlgaKuvs** [comment]
After placing an order, the user can see all completed orders in his profile in the Order History section. When he clicks on the order number, detailed information about the order opens, and "Leave Review" button appears next to each item. When the user clicks on "Leave Review" button, a form opens in which the user can write his name, a comment about the product, and also rate the product (from 1 to 5). When a user submits a review, a message appears indicating that the review will be published after admin approval. "Leave Review" button is accessible only from the user profile. Not logged in user is redirected to the login page when trying to load the review page via a direct link.
