### ISSUE TITLE
USER STORY: Show Reviews

### ISSUE THREAD

**Issue by OlgaKuvs** [OlgaKuvs/T-studio#18]
Epic: #16 

As a  **customer**, I can **view a list of reviews for each product** so that **I can find out if customers are satisfied with the product.**

**Acceptance Criteria:**

The page with detailed information about the product displays a list of all reviews for it.

**Tasks:**
* [x] create a function to show reviews
* [x] update product detail page to display all review information
* [x] add html and styles to show rating stars

**Comment by OlgaKuvs** [comment]
A list of all approved reviews is displayed on the detailed product description page.
