### ISSUE TITLE
USER STORY: View product rating

### ISSUE THREAD

**Issue by OlgaKuvs** [OlgaKuvs/T-studio#19]
As a  **customer**, I can **view each product rating** to **know how good this product is**.

**Acceptance Criteria:**

The average star rating (from 1 to 5) is displayed for each product.

**Tasks:**

* [x] implement functionality to calculate average rating.
* [x] show the average rating for each product.
* [x] ensure that the average rating is based only on admin approved reviews.

**Comment by OlgaKuvs** [comment]
The rating for each product is reflected in the form of stars (from 1 to 5) and is calculated as the average rating value of all approved reviews. The product rating is reflected both on the main page of the store and the detailed description page of the item.
