### ISSUE TITLE
USER STORY: Product View

### ISSUE THREAD

**Issue by OlgaKuvs** [OlgaKuvs/T-studio#2]
Epic: #1 

As a  **user**, I can **view a list of products** so that **I can decide if I wish to purchase anything.**

**Acceptance Criteria:**

Users should be able to see all products if they choose to regardless of category.

**Tasks:**

* [x] create products view
* [x] create a products template
* [x] create a products model
* [x] add sample products to the store
* [x] test products are showing up correctly

**Comment by OlgaKuvs** [comment]
Without logging in the user can access a list of products. The product listing includes a product image, name, price, category and rating. The user can navigate through categories by clicking on the category name at the dropdown menu, at the top of the store pages or in the information about each product.
