### ISSUE TITLE
USER STORY: Manage Delivery Rates

### ISSUE THREAD

**Issue by OlgaKuvs** [OlgaKuvs/T-studio#27]
Epic: #23 

As a **store owner**, I want to be able **to set and change shipping rates** to **match carrier's rates.**

**Tasks:**

* [x] create a model for order weight and shipping costs.
* [x] add functionality to calculate shipping costs.
* [x] correctly display shipping costs on html pages.

**Comment by OlgaKuvs** [comment]
The store owner can access the "Shipping" table through the Django admin panel and change the shipping cost to match the carrier's rates. The cost of order delivery is calculated based on the weight of each item and the carrier’s prices.
