### ISSUE TITLE
USER STORY: Contact Us Page

### ISSUE THREAD

**Issue by OlgaKuvs** [OlgaKuvs/T-studio#32]
Epic: #28 

As a  **customer**, I can **contact the business owner** so that **I can communicate with a person.**

**Tasks:**

* [x] create Contact Us page with contact information and contact form.
* [x] add form functionality.
* [x] ensure that all form data is recorded correctly to the database.

**Comment by OlgaKuvs** [comment]
The business owner receives confirmation of the new contact form to their email address.

**Comment by OlgaKuvs** [comment]
"Contact Us" page is accessible from the main navigation bar at the top of each page, and a link to this page is added at the end of each "Our services" section for customer convenience. On the "Contact Us" page, the customer can fill out a "Contact Form" and ask any question to the business owner.
