### ISSUE TITLE
USER STORY: SEO

### ISSUE THREAD

**Issue by OlgaKuvs** [OlgaKuvs/T-studio#35]
Epic: #33 

As a **store owner**, I want **sitemap.xml file,  robots.txt file, keywords and Meta tags to boost the SEO**  so that **this business reflects as professional on google search and this website is crawlable by google spiders.**

**Tasks:**

* [x] add robots.txt file
* [x] add sitemap.xml file
* [x] create a minimum of 5 long tail and short tail keywords chosen to boost the SEO of this business and placed in copy throughout the pages.
* [x] add all relevant meta tags

**Comment by OlgaKuvs** [comment]
To boost the SEO of this business, keywords were created and placed on all pages. Meta tags were added to the website to display relevant and correct information in searches so that this business would appear professional in Google searches and so that the clients would trust it. So that this site can be crawled by Google robots, a robots.txt file was created. Created a sitemap so all site links are disclosed for submission to Google.
